# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: medical_ai.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'medical_ai.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10medical_ai.proto\x12\nmedical_ai\"n\n\x0f\x41nalysisRequest\x12\x19\n\x11patient_text_data\x18\x01 \x01(\t\x12\x14\n\x0cimage_base64\x18\x02 \x01(\t\x12\x0e\n\x06stream\x18\x03 \x01(\x08\x12\x1a\n\x12patient_department\x18\x04 \x01(\t\"L\n\x0e\x41nalysisReport\x12\x19\n\x11structured_report\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"1\n\x0bStreamChunk\x12\x12\n\nchunk_data\x18\x01 \x01(\x0c\x12\x0e\n\x06is_end\x18\x02 \x01(\x08\x32\x64\n\x10MedicalAIService\x12P\n\x16ProcessMedicalAnalysis\x12\x1b.medical_ai.AnalysisRequest\x1a\x17.medical_ai.StreamChunk0\x01\x42\x18\n\x0b\x63om.exampleH\x01\xf8\x01\x01\xa2\x02\x03MEDb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'medical_ai_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.exampleH\001\370\001\001\242\002\003MED'
  _globals['_ANALYSISREQUEST']._serialized_start=32
  _globals['_ANALYSISREQUEST']._serialized_end=142
  _globals['_ANALYSISREPORT']._serialized_start=144
  _globals['_ANALYSISREPORT']._serialized_end=220
  _globals['_STREAMCHUNK']._serialized_start=222
  _globals['_STREAMCHUNK']._serialized_end=271
  _globals['_MEDICALAISERVICE']._serialized_start=273
  _globals['_MEDICALAISERVICE']._serialized_end=373
# @@protoc_insertion_point(module_scope)
