# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import medical_ai_pb2 as medical__ai__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in medical_ai_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MedicalAIServiceStub(object):
    """4. gRPC服务接口
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessMedicalAnalysisSync = channel.unary_unary(
                '/medical_ai.MedicalAIService/ProcessMedicalAnalysisSync',
                request_serializer=medical__ai__pb2.AnalysisRequest.SerializeToString,
                response_deserializer=medical__ai__pb2.AnalysisReport.FromString,
                _registered_method=True)
        self.ProcessMedicalAnalysis = channel.unary_stream(
                '/medical_ai.MedicalAIService/ProcessMedicalAnalysis',
                request_serializer=medical__ai__pb2.AnalysisRequest.SerializeToString,
                response_deserializer=medical__ai__pb2.StreamChunk.FromString,
                _registered_method=True)


class MedicalAIServiceServicer(object):
    """4. gRPC服务接口
    """

    def ProcessMedicalAnalysisSync(self, request, context):
        """非流式（同步）接口 - 推荐使用
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessMedicalAnalysis(self, request, context):
        """流式接口 - 保留用于特殊场景
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MedicalAIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessMedicalAnalysisSync': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessMedicalAnalysisSync,
                    request_deserializer=medical__ai__pb2.AnalysisRequest.FromString,
                    response_serializer=medical__ai__pb2.AnalysisReport.SerializeToString,
            ),
            'ProcessMedicalAnalysis': grpc.unary_stream_rpc_method_handler(
                    servicer.ProcessMedicalAnalysis,
                    request_deserializer=medical__ai__pb2.AnalysisRequest.FromString,
                    response_serializer=medical__ai__pb2.StreamChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'medical_ai.MedicalAIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('medical_ai.MedicalAIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MedicalAIService(object):
    """4. gRPC服务接口
    """

    @staticmethod
    def ProcessMedicalAnalysisSync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/medical_ai.MedicalAIService/ProcessMedicalAnalysisSync',
            medical__ai__pb2.AnalysisRequest.SerializeToString,
            medical__ai__pb2.AnalysisReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessMedicalAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/medical_ai.MedicalAIService/ProcessMedicalAnalysis',
            medical__ai__pb2.AnalysisRequest.SerializeToString,
            medical__ai__pb2.StreamChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
